name: Extract and build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract unigen-rs.zip
        run: unzip -o unigen-rs.zip -d .
